# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=9, null=True)),
                ('tipodoc_cliente', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10)),
                ('numdoc_cliente', models.IntegerField(blank=True, null=True)),
                ('email_cliente', models.EmailField(max_length=50, null=True)),
                ('genero_cliente', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10)),
                ('fechasuscripcion_cliente', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
    ]
