# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_almacen', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Almacens',
                'verbose_name': 'Almacen',
                'ordering': ['nombre_almacen'],
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cajeros',
                'verbose_name': 'Cajero',
                'ordering': ['numero_caja'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_categoria', models.TextField(blank=True, max_length=350, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, null=True)),
                ('tipocomprobante', models.CharField(choices=[('FACTURA', 'FACTURA'), ('BOLETA', 'BOLETA')], default='FACTURA', max_length=10)),
                ('almacen_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Almacen')),
                ('cajero_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Cajero')),
            ],
            options={
                'verbose_name_plural': 'Ingresos',
                'verbose_name': 'Ingreso',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_inicial', models.IntegerField(blank=True, default=0)),
                ('stock_actual', models.IntegerField(blank=True, default=0)),
                ('fecha_vencimiento', models.DateField(auto_now_add=True, null=True)),
                ('ingreso_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Ingreso')),
            ],
            options={
                'verbose_name_plural': 'IngresoDetalles',
                'verbose_name': 'IngresoDetalle',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_producto', models.TextField(blank=True, max_length=350, null=True)),
                ('categoria_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=9, null=True)),
                ('tipodoc_proveedor', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10)),
                ('numdoc_proveedor', models.IntegerField(blank=True, null=True)),
                ('email_proveedor', models.EmailField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedors',
                'verbose_name': 'Proveedor',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_trabajador', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_trabajador', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_trabajador', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_trabajador', models.CharField(blank=True, max_length=9, null=True)),
                ('tipodoc_trabajador', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10)),
                ('numdoc_trabajador', models.IntegerField(blank=True, null=True)),
                ('email_trabajador', models.EmailField(max_length=50, null=True)),
                ('genero_trabajador', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Trabajadors',
                'verbose_name': 'Trabajador',
                'ordering': ['nombre_trabajador'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('CUOTAS', 'CUOTAS'), ('CONTADO', 'CONTADO')], default='CONTADO', max_length=10)),
                ('fecha_venta', models.DateField(auto_now_add=True, null=True)),
                ('tipocomprobante', models.CharField(choices=[('FACTURA', 'FACTURA'), ('BOLETA', 'BOLETA')], default='FACTURA', max_length=10)),
                ('almacen_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Almacen')),
                ('cajero_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Cajero')),
                ('cliente_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'verbose_name': 'Venta',
                'ordering': ['fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.IntegerField(blank=True, default=0)),
                ('ingresodetalles_fk', models.ManyToManyField(blank=True, null=True, related_name='ingresodetalle_related', to='ventaz_app.IngresoDetalle')),
                ('venta_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Venta')),
            ],
            options={
                'verbose_name_plural': 'VentaDetalles',
                'verbose_name': 'VentaDetalle',
                'ordering': ['precio_venta'],
            },
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='productos_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='producto_related', to='ventaz_app.Producto'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='proveedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Proveedor'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='trabajador_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Trabajador'),
        ),
    ]
