# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0002_auto_20171130_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='almacen_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.Almacen'),
        ),
    ]
