# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0003_cajero_almacen_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['tipocomprobante'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='ingresodetalle',
            options={'ordering': ['estado'], 'verbose_name': 'IngresoDetalle', 'verbose_name_plural': 'IngresoDetalles'},
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
