# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0004_auto_20171130_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['tipo_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'ordering': ['estado'], 'verbose_name': 'VentaDetalle', 'verbose_name_plural': 'VentaDetalles'},
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
