# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0005_auto_20171130_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajero',
            name='almacen_fk',
        ),
        migrations.RemoveField(
            model_name='cajero',
            name='trabajador_fk',
        ),
    ]
