# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0006_auto_20171201_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('almacens_fk', models.ManyToManyField(blank=True, null=True, related_name='almacen_related', to='ventaz_app.Almacen')),
                ('cajeros_fk', models.ManyToManyField(blank=True, null=True, related_name='cajero_related', to='ventaz_app.Cajero')),
            ],
            options={
                'verbose_name_plural': 'TrabajadorDetalles',
                'ordering': ['estado'],
                'verbose_name': 'TrabajadorDetalle',
            },
        ),
    ]
