# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0007_trabajadordetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadordetalle',
            name='almacens_fk',
        ),
        migrations.RemoveField(
            model_name='trabajadordetalle',
            name='cajeros_fk',
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['estado'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadors'},
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='apellidos_trabajador',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='direccion_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='email_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='genero_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='nombre_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='numdoc_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='telefono_trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tipodoc_trabajador',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='almacens_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='almacen_related', to='ventaz_app.Almacen'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='cajeros_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='cajero_related', to='ventaz_app.Cajero'),
        ),
        migrations.DeleteModel(
            name='TrabajadorDetalle',
        ),
    ]
