# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0008_auto_20171201_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['apellidos_Trabajador'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadors'},
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='estado',
            new_name='apellidos_Trabajador',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='direccion_Trabajador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='email_Trabajador',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fechasuscripcion_Trabajador',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='genero_Trabajador',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nombre_Trabajador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='numdoc_Trabajador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefono_Trabajador',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
