# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0009_auto_20171201_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['apellidos_trabajador'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadors'},
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='apellidos_Trabajador',
            new_name='apellidos_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='direccion_Trabajador',
            new_name='direccion_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='email_Trabajador',
            new_name='email_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='fechasuscripcion_Trabajador',
            new_name='fechasuscripcion_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='genero_Trabajador',
            new_name='genero_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='nombre_Trabajador',
            new_name='nombre_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='numdoc_Trabajador',
            new_name='numdoc_trabajador',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='telefono_Trabajador',
            new_name='telefono_trabajador',
        ),
    ]
