# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0011_remove_cajero_numero_piso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_en', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_en', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_en', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'EstablecimientoNegocios',
                'ordering': ['nombre_en'],
                'verbose_name': 'EstablecimientoNegocio',
            },
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['estado'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='cajero_fk',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cajeros_fk',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='almacen_fk',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cajero_fk',
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA'), ('ABIERTA', 'ABIERTA')], default='CERRADA', max_length=10),
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='establecimientonegocios_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='establecimientonegocio_related', to='ventaz_app.EstablecimientoNegocio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='establecimientonegocio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaz_app.EstablecimientoNegocio'),
        ),
    ]
