# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0013_auto_20171201_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresodetalle',
            options={'verbose_name': 'IngresoDetalle', 'verbose_name_plural': 'IngresoDetalles'},
        ),
    ]
