# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0014_auto_20171201_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
