# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0015_auto_20171201_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='almacen_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_related', to='ventaz_app.Almacen'),
        ),
    ]
