# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0017_auto_20171201_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresodetalle',
            name='estado',
        ),
    ]
