# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0018_remove_ingresodetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
