# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0019_ingreso_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='estado',
        ),
    ]
