# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0020_remove_ingreso_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacens'},
        ),
    ]
