# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0021_auto_20171201_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['nombre_almacen'], 'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacens'},
        ),
    ]
