# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0023_auto_20171202_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='descuento',
        ),
    ]
