# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0026_auto_20171202_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresodetalle',
            name='ingreso_fk',
        ),
        migrations.RemoveField(
            model_name='ingresodetalle',
            name='productos_fk',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA'), ('ABIERTA', 'ABIERTA')], default='CERRADA', max_length=10),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_vencimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='productos_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='producto_related', to='ventaz_app.Producto'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='stock_actual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='stock_inicial',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='IngresoDetalle',
        ),
    ]
