# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0027_auto_20171202_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='productos_fk',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='producto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_related', to='ventaz_app.Producto'),
        ),
    ]
