# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaz_app', '0029_ingreso_producto_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='fechasuscripcion_trabajador',
        ),
    ]
